---
 - name: This playbook is will use ansible variables decleration - 1
   hosts: webservers
   become: True
   vars:
     package: vim

   tasks:
     - name: To install the vim editor in remote servers
       copy: src=/opt/playbooks/copy.yml dest=
