---
 - name: This playbook is will use ansible for loops
   hosts: webservers
   become: True

   tasks:
     - name: To print the servers which are part of this playbook execution
       debug: var=play_hosts
