---
 - name: This playbook will print the facts which are collected as part of each playbook execution
   hosts: webservers
   become: True

   tasks:
     - name: to print the facts info
       yum:
         name: unzip
         state: installed
       when: 
         - ansible_pkg_mgr == "yum"
         - ansible_os_family == "RedHat"

     - name: to print the facts info
       yum:
         name: unzip
         state: installed
       when: (ansible_pkg_mgr == "yum" and ansible_os_family == "CentOS") or (ansible_pkg_mgr == "yum" and ansible_os_family == "RedHat")

     - name: To install unzip in ubuntu servers
       apt:
         name: unzip
         state: installed
       when: 
         - ansible_pkg_mgr == "apt"
         - ansible_os_family == "Ubuntu"
